# 主配置文件

server:
  tomcat:
    uri-encoding: UTF-8
    # 请求正文的最大大小
    max-swallow-size: 100MB

spring:
  profiles:
    # prod 使用环境: dev: 开发环境, prod: 生产环境
    active: dev
  jpa:
    hibernate:
      # 关闭 JPA 模型生成表的机制
      ddl-auto: none
  jackson:
    # 配置序列化的 key 为下划线拼接的形式, 如: xxx_xxx
    property-naming-strategy: SNAKE_CASE
    serialization:
      # 配置返回的时间为时间戳形式(毫秒数)
      WRITE_DATES_AS_TIMESTAMPS: true
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  resources:
    # 关闭静态资源的映射
    add-mappings: false

# knife4j 配置
knife4j:
  title: xxx 接口 API                           # API 页面标题
  description: xxx 的 API 接口文档               # API 页面描述
  version: 0.0.1                               # API 版本号
  terms-of-service-url: https://www.xxx.com/   # API 服务条款地址
  base-package: cn.xilikeli.staging.controller # API 接口包路径
  # 作者(联系人)信息
  name: 联系人名称                  # 名称
  url: https://www.xxx.com/       # 个人站点地址
  email: xxx@xxx.com              # 联系邮箱