# 主配置文件

server:
  tomcat:
    uri-encoding: UTF-8
    # 请求正文的最大大小
    max-swallow-size: 100MB

spring:
  profiles:
    # prod 使用环境: dev: 开发环境, prod: 生产环境
    active: dev
  jpa:
    hibernate:
      # 关闭 JPA 模型生成表的机制
      ddl-auto: none
  jackson:
    # 配置序列化的 key 为下划线拼接的形式, 如: xxx_xxx
    property-naming-strategy: SNAKE_CASE
    serialization:
      # 配置返回的时间为时间戳形式(毫秒数)
      WRITE_DATES_AS_TIMESTAMPS: true
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  resources:
    # 关闭静态资源的映射
    add-mappings: false

# 微信校验参数(填写你的小程序 AppId 和 AppSecret)
we-chat:
  appid: xxxxxxxxxxxxxxxxxxx
  appsecret: xxxxxxxxxxxxxxxxxxx
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code