# 生产环境配置

server:
  # 服务端口
  port: 8082

spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型: HikariCP
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长(毫秒), 超过这个时长还没可用的连接则发生 SQLException, 默认: 30 秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长(毫秒), 超时则被释放(retired), 默认: 10 分钟(600000 ms)
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长(毫秒), 超时而且没被使用则被释放(retired), 默认: 30 分钟(1800000 ms)
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 驱动
    url: jdbc:mysql://localhost:3306/staging?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root   # mysql 用户名
    password: 123456 # mysql 密码

# 项目自定义配置项
staging:
  cors-allowed-origin: http://localhost:8083 # 允许的跨域域名
  security: # 安全性配置
    jwt-key: fushengruomengstaging # 用于生成 JWT 令牌的 key
    token-expire-time: 7200        # 令牌过期时间

# knife4j 配置
knife4j:
  open: false                                   # 是否开启 knife4j(通过条件注解的方式控制)
  title: xxx 接口 API                           # API 页面标题
  description: xxx 的 API 接口文档               # API 页面描述
  version: 0.0.1                               # API 版本号
  terms-of-service-url: https://www.xxx.com/   # API 服务条款地址
  base-package: cn.xilikeli.staging.controller # API 接口包路径
  # 作者(联系人)信息
  name: 联系人名称                  # 名称
  url: https://www.xxx.com/       # 个人站点地址
  email: xxx@xxx.com              # 联系邮箱